from django.db import models

class Record(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    age = models.IntegerField(blank=True,null=True) 
    gender = models.CharField(max_length=10, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], blank=True, null=True)
    NATIONALITIES = [
    ('Afghan', 'Afghan'),
    ('Albanian', 'Albanian'),
    ('Algerian', 'Algerian'),
    ('American', 'American'),
    ('Andorran', 'Andorran'),
    ('Angolan', 'Angolan'),
    ('Antiguan and Barbudan', 'Antiguan and Barbudan'),
    ('Argentine', 'Argentine'),
    ('Armenian', 'Armenian'),
    ('Aruban', 'Aruban'),
    ('Australian', 'Australian'),
    ('Austrian', 'Austrian'),
    ('Azerbaijani', 'Azerbaijani'),
    ('Bahamian', 'Bahamian'),
    ('Bahraini', 'Bahraini'),
    ('Bangladeshi', 'Bangladeshi'),
    ('Barbadian', 'Barbadian'),
    ('Basque', 'Basque'),
    ('Belarusian', 'Belarusian'),
    ('Belgian', 'Belgian'),
    ('Belizean', 'Belizean'),
    ('Beninese', 'Beninese'),
    ('Bermudian', 'Bermudian'),
    ('Bhutanese', 'Bhutanese'),
    ('Bolivian', 'Bolivian'),
    ('Bosniak', 'Bosniak'),
    ('Bosnian and Herzegovinian', 'Bosnian and Herzegovinian'),
    ('Botswana', 'Botswana'),
    ('Brazilian', 'Brazilian'),
    ('Breton', 'Breton'),
    ('British', 'British'),
    ('British Virgin Islander', 'British Virgin Islander'),
    ('Bruneian', 'Bruneian'),
    ('Bulgarian', 'Bulgarian'),
    ('Macedonian Bulgarian', 'Macedonian Bulgarian'),
    ('Burkinabé', 'Burkinabé'),
    ('Burmese', 'Burmese'),
    ('Burundian', 'Burundian'),
    ('Cambodian', 'Cambodian'),
    ('Cameroonian', 'Cameroonian'),
    ('Canadian', 'Canadian'),
    ('Catalan', 'Catalan'),
    ('Cape Verdean', 'Cape Verdean'),
    ('Caymanian', 'Caymanian'),
    ('Chaldean', 'Chaldean'),
    ('Chadian', 'Chadian'),
    ('Chilean', 'Chilean'),
    ('Chinese', 'Chinese'),
    ('Colombian', 'Colombian'),
    ('Comorian', 'Comorian'),
    ('Congolese (DRC)', 'Congolese (DRC)'),
    ('Congolese (RotC)', 'Congolese (RotC)'),
    ('Costa Rican', 'Costa Rican'),
    ('Croat', 'Croat'),
    ('Cuban', 'Cuban'),
    ('Cypriot', 'Cypriot'),
    ('Czech', 'Czech'),
    ('Danish', 'Danish'),
    ('Greenlander', 'Greenlander'),
    ('Djiboutian', 'Djiboutian'),
    ('Dominican (Commonwealth)', 'Dominican (Commonwealth)'),
    ('Dominican (Republic)', 'Dominican (Republic)'),
    ('Dutch', 'Dutch'),
    ('East Timorese', 'East Timorese'),
    ('Ecuadorian', 'Ecuadorian'),
    ('Egyptian', 'Egyptian'),
    ('Emirati', 'Emirati'),
    ('English', 'English'),
    ('Equatoguinean', 'Equatoguinean'),
    ('Eritrean', 'Eritrean'),
    ('Estonian', 'Estonian'),
    ('Ethiopian', 'Ethiopian'),
    ('Falkland Islander', 'Falkland Islander'),
    ('Faroese', 'Faroese'),
    ('Fijian', 'Fijian'),
    ('Finn', 'Finn'),
    ('Finnish Swedish', 'Finnish Swedish'),
    ('Filipino', 'Filipino'),
    ('French citizen', 'French citizen'),
    ('Gabonese', 'Gabonese'),
    ('Gambian', 'Gambian'),
    ('Georgian', 'Georgian'),
    ('German', 'German'),
    ('Baltic German', 'Baltic German'),
    ('Ghanaian', 'Ghanaian'),
    ('Gibraltarian', 'Gibraltarian'),
    ('Greek', 'Greek'),
    ('Greek Macedonian', 'Greek Macedonian'),
    ('Grenadian', 'Grenadian'),
    ('Guatemalan', 'Guatemalan'),
    ('Guianese (French)', 'Guianese (French)'),
    ('Guinean', 'Guinean'),
    ('Guinea-Bissau national', 'Guinea-Bissau national'),
    ('Guyanese', 'Guyanese'),
    ('Haitian', 'Haitian'),
    ('Honduran', 'Honduran'),
    ('Hong Konger', 'Hong Konger'),
    ('Hungarian', 'Hungarian'),
    ('Icelander', 'Icelander'),
    ('I-Kiribati', 'I-Kiribati'),
    ('Indian', 'Indian'),
    ('Indonesian', 'Indonesian'),
    ('Iranian', 'Iranian'),
    ('Iraqi', 'Iraqi'),
    ('Irish', 'Irish'),
    ('Israeli', 'Israeli'),
    ('Italian', 'Italian'),
    ('Ivorian', 'Ivorian'),
    ('Jamaican', 'Jamaican'),
    ('Japanese', 'Japanese'),
    ('Jordanian', 'Jordanian'),
    ('Kazakh', 'Kazakh'),
    ('Kenyan', 'Kenyan'),
    ('Kosovar', 'Kosovar'),
    ('Kuwaiti', 'Kuwaiti'),
    ('Kyrgyz', 'Kyrgyz'),
    ('Lao', 'Lao'),
    ('Latvian', 'Latvian'),
    ('Lebanese', 'Lebanese'),
    ('Liberian', 'Liberian'),
    ('Libyan', 'Libyan'),
    ('Liechtensteiner', 'Liechtensteiner'),
    ('Lithuanian', 'Lithuanian'),
    ('Luxembourger', 'Luxembourger'),
    ('Macao', 'Macao'),
    ('Macedonian', 'Macedonian'),
    ('Malagasy', 'Malagasy'),
    ('Malawian', 'Malawian'),
    ('Malaysian', 'Malaysian'),
    ('Maldivian', 'Maldivian'),
    ('Malian', 'Malian'),
    ('Maltese', 'Maltese'),
    ('Manx', 'Manx'),
    ('Marshallese', 'Marshallese'),
    ('Mauritanian', 'Mauritanian'),
    ('Mauritian', 'Mauritian'),
    ('Mexican', 'Mexican'),
    ('Micronesian', 'Micronesian'),
    ('Moldovan', 'Moldovan'),
    ('Monégasque', 'Monégasque'),
    ('Mongolian', 'Mongolian'),
    ('Montenegrin', 'Montenegrin'),
    ('Moroccan', 'Moroccan'),
    ('Mozambican', 'Mozambican'),
    ('Namibian', 'Namibian'),
    ('Nauruan', 'Nauruan'),
    ('Nepalese', 'Nepalese'),
    ('New Zealander', 'New Zealander'),
    ('Nicaraguan', 'Nicaraguan'),
    ('Nigerien', 'Nigerien'),
    ('Nigerian', 'Nigerian'),
    ('Norwegian', 'Norwegian'),
    ('Omani', 'Omani'),
    ('Pakistani', 'Pakistani'),
    ('Palauan', 'Palauan'),
    ('Palestinian', 'Palestinian'),
    ('Panamanian', 'Panamanian'),
    ('Papua New Guinean', 'Papua New Guinean'),
    ('Paraguayan', 'Paraguayan'),
    ('Peruvian', 'Peruvian'),
    ('Pole', 'Pole'),
    ('Portuguese', 'Portuguese'),
    ('Puerto Rican', 'Puerto Rican'),
    ('Qatari', 'Qatari'),
    ('Quebecer', 'Quebecer'),
    ('Réunionnai', 'Réunionnai'),
    ('Romanian', 'Romanian'),
    ('Russian', 'Russian'),
    ('Baltic Russian', 'Baltic Russian'),
    ('Rwandan', 'Rwandan'),
    ('Saint Kitt and Nevi', 'Saint Kitt and Nevi'),
    ('Saint Lucian', 'Saint Lucian'),
    ('Salvadoran', 'Salvadoran'),
    ('Sammarinese', 'Sammarinese'),
    ('Samoan', 'Samoan'),
    ('São Tomé and Príncipe', 'São Tomé and Príncipe'),
    ('Saudi', 'Saudi'),
    ('Scot', 'Scot'),
    ('Senegalese', 'Senegalese'),
    ('Serb', 'Serb'),
    ('Seychelloi', 'Seychelloi'),
    ('Sierra Leonean', 'Sierra Leonean'),
    ('Singaporean', 'Singaporean'),
    ('Slovak', 'Slovak'),
    ('Slovene', 'Slovene'),
    ('Solomon Islander', 'Solomon Islander'),
    ('Somali', 'Somali'),
    ('Somalilander', 'Somalilander'),
    ('Sotho', 'Sotho'),
    ('South African', 'South African'),
    ('Spaniard', 'Spaniard'),
    ('Sri Lankan', 'Sri Lankan'),
    ('Sudanese', 'Sudanese'),
    ('Surinamese', 'Surinamese'),
    ('Swazi', 'Swazi'),
    ('Swede', 'Swede'),
    ('Swiss', 'Swiss'),
    ('Syriac', 'Syriac'),
    ('Syrian', 'Syrian'),
    ('Taiwanese', 'Taiwanese'),
    ('Tamil', 'Tamil'),
    ('Tajik', 'Tajik'),
    ('Tanzanian', 'Tanzanian'),
    ('Thai', 'Thai'),
    ('Tibetan', 'Tibetan'),
    ('Tobagonian', 'Tobagonian'),
    ('Togolese', 'Togolese'),
    ('Tongan', 'Tongan'),
    ('Trinidadian', 'Trinidadian'),
    ('Tunisian', 'Tunisian'),
    ('Turk', 'Turk'),
    ('Tuvaluan', 'Tuvaluan'),
    ('Ugandan', 'Ugandan'),
    ('Ukrainian', 'Ukrainian'),
    ('Uruguayan', 'Uruguayan'),
    ('Uzbek', 'Uzbek'),
    ('Vanuatuan', 'Vanuatuan'),
    ('Venezuelan', 'Venezuelan'),
    ('Vietnamese', 'Vietnamese'),
    ('Vincentian', 'Vincentian'),
    ('Welsh', 'Welsh'),
    ('Yemeni', 'Yemeni'),
    ('Zambian', 'Zambian'),
    ('Zimbabwean', 'Zimbabwean'),]   
    nationality = models.CharField(max_length=125, choices=NATIONALITIES, blank=True, null=True)

    # Add a file field for uploading files (e.g., profile picture)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    