# Generated by Django 4.2.6 on 2023-10-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_record_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='country',
        ),
        migrations.AddField(
            model_name='record',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
